language: crystal

addons:
  apt:
    packages:
      - libsdl2-dev
      - libgl1-mesa-dev
      - libfontconfig1-dev
      - libopenal-dev
      - libsndfile1-dev
      - libmpg123-dev
      # For C++
      - cmake

before_script:
  - |
    echo $PWD
    cd ..
    git clone --depth=1 --single-branch --branch c_library https://github.com/cyberarm/gosu
    cd gosu

    mkdir -p cmake/build
    cd cmake/build
    cmake ..
    make
    sudo make install
    cd ../..

    cd ../gosu.cr

git:
  depth: 1

script:
  - crystal spec
  - crystal tool format --check
