dist: bionic
language: crystal
crystal:
  - latest

addons:
  apt:
    packages:
      - libsdl2-dev
      - libgl1-mesa-dev
      - libfontconfig1-dev
      - libopenal-dev
      - libsndfile1-dev
      - libmpg123-dev
      # For C++
      - cmake
services:
  - xvfb

before_script:
  - |
    echo $PWD
    cd ..
    git clone --depth=1 --single-branch --branch master https://github.com/gosu/gosu
    cd gosu

    mkdir -p build
    cd build
    cmake ..
    sed -i 's@set(CMAKE_INSTALL_PREFIX "/usr/local")@set(CMAKE_INSTALL_PREFIX "/usr")@g' cmake_install.cmake
    make
    sudo make install
    cd ..

    cd ../gosu.cr

git:
  depth: 1

script:
  - echo $PWD
  - crystal spec
  - crystal tool format --check
