name: Crystal CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install Gosu dependencies
      run: |
        apt-get update -y -qq
        apt-get install -y libsdl2-dev libgl1-mesa-dev libfontconfig1-dev libopenal-dev libsndfile1-dev libmpg123-dev cmake xvfb
    - name: Install Gosu
      run: |
        echo $PWD
        cd ..
        git clone --depth=1 --single-branch --branch master https://github.com/gosu/gosu
        cd gosu

        sed -i 's/^cmake_policy/# &/' cmake/GosuConfig.cmake
        mkdir -p build
        cd build
        cmake ..
        sed -i 's@set(CMAKE_INSTALL_PREFIX "/usr/local")@set(CMAKE_INSTALL_PREFIX "/usr")@g' cmake_install.cmake
        make
        make install
        cd ..

        cd ../gosu.cr
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: xvfb-run crystal spec
