name: Crystal CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v1
    - name: Install Gosu dependencies
      run: |
        apt-get update -y -qq
        apt-get install libsdl2-dev libgl1-mesa-dev libfontconfig1-dev libopenal-dev libsndfile1-dev libmpg123-dev cmake
    - name: Install Gosu
      run: |
        echo $PWD
        cd ..
        git clone --depth=1 --single-branch --branch c_library https://github.com/cyberarm/gosu
        cd gosu

        mkdir -p cmake/build
        cd cmake/build
        cmake ..
        sed -i 's@set(CMAKE_INSTALL_PREFIX "/usr/local")@set(CMAKE_INSTALL_PREFIX "/usr")@g' cmake_install.cmake
        make
        make install
        cd ../..

        cd ../gosu.cr
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
